name: smart_rental_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # 确保 flutter: 在 dependencies: 下面缩进2个空格
  flutter:
    sdk: flutter

  # 确保这些包和 flutter: 在同一缩进级别
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # 你这里的 assets 声明是完全正确的！
  assets:
    - assets/images/my_logo.png